name: Executar Robô CNJ - Hugging Face

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 6 * * *' # Roda diariamente

jobs:
  executar:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # Permite rodar até 6 horas

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar bibliotecas
        run: |
          pip install requests duckdb huggingface_hub

      - name: Rodar o script Python
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PYTHONUNBUFFERED: "1"
        run: |
          python -u robo_python_2_arq.py
