name: Executar Robô CNJ

on:
  workflow_dispatch: # Permite rodar manualmente
  # schedule:
  #   - cron: '0 3 * * *' # Exemplo: roda todo dia às 03h

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install requests duckdb

      - name: Rodar script
        env:
          URL_BANCO: ${{ secrets.URL_BANCO }}
        run: |
          python robo_python_2_arq.py
